baseURL = "https://verbose-lamp.netlify.app/g"
languageCode = "en-us"
title = "Look & Point"
theme = "hugo-book"

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true